version: '3'

services:

  www:
    hostname: www
    build: './cloud/public/www'
    restart: always
    volumes:
      - './cloud/public/www/html:/usr/share/nginx/html'
      - './data/upload:/usr/share/nginx/html/files'
    ports:
      - '80:80'

  panel:
    hostname: panel
    build: './cloud/public/panel'
    restart: always
    volumes:
      - './cloud/public/panel/html:/usr/share/nginx/html/panel'

  api_upload:
    hostname: api_upload
    build: './cloud/api/upload'
    restart: always
    volumes:
      - './cloud/api/upload:/go/src'
      - './cloud/api/commons:/julia_store/commons'
      - './logs:/julia_store/logs'
      - './data:/julia_store/data'

  api_users_login:
    hostname: api_users_login
    build: './cloud/api/users-login'
    restart: always
    volumes:
      - './cloud/api/users-login:/julia_store/app'
      - './cloud/api/commons:/julia_store/commons'
      - './logs/api_users_login:/julia_store/logs'
      - './data:/julia_store/data'

  api_users_register:
    hostname: api_users_register
    build: './cloud/api/users-register'
    restart: always
    volumes:
      - './cloud/api/users-register:/julia_store/app'
      - './cloud/api/commons:/julia_store/commons'
      - './logs/api_users_register:/julia_store/logs'
      - './data:/julia_store/data'

  api_providers_list:
    hostname: api_providers_list
    build: './cloud/api/providers-list'
    restart: always
    volumes:
      - './cloud/api/providers-list:/julia_store/app'
      - './cloud/api/commons:/julia_store/commons'
      - './logs/api_providers_list:/julia_store/logs'
      - './data:/julia_store/data'

  api_providers_create:
    hostname: api_providers_create
    build: './cloud/api/providers-create'
    restart: always
    volumes:
      - './cloud/api/providers-create:/julia_store/app'
      - './cloud/api/commons:/julia_store/commons'
      - './logs/api_providers_create:/julia_store/logs'
      - './data:/julia_store/data'

  api_products_list:
    hostname: api_products_list
    build: './cloud/api/products-list'
    restart: always
    volumes:
      - './cloud/api/products-list:/julia_store/app'
      - './cloud/api/commons:/julia_store/commons'
      - './logs/api_products_list:/julia_store/logs'
      - './data:/julia_store/data'

  api_products_create:
    hostname: api_products_create
    build: './cloud/api/products-create'
    restart: always
    volumes:
      - './cloud/api/products-create:/julia_store/app'
      - './cloud/api/commons:/julia_store/commons'
      - './logs/api_products_create:/julia_store/logs'
      - './data:/julia_store/data'

